### ISSUE TITLE
Time vocabulary deployment

### ISSUE THREAD

**Issue by AlasdairGray** [streamreasoning/RSP-QL#15]
We should set up a LODE page or neologism (if it is still available) to allow us to more easily discuss the vocabulary. Examples
* [LODE](http://www.essepuntato.it/lode) an example deployment can be found with the [PAV vocabulary](http://purl.org/pav/html) which uses purls
* [Neologism](http://neologism.deri.ie/showcase) an example deployment can be found on the wikipathways hosted [gene ontology](http://vocabularies.wikipathways.org/go#)

**Comment by beta2k** [comment]
with LODE we can even do it on the fly: http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/streamreasoning/RSP-QL/master/TimeVocab.owl

this should be fine for discussion. when we agree on the vocab, we can then decide on a namespace: purl, w3c community group, streamreasoning.org, etc.

**Comment by AlasdairGray** [comment]
I keep getting a gateway timeout error when trying to follow the link above.

**Comment by beta2k** [comment]
for me it works now. can you try again?
else i will contact the admin of the service.

**Comment by AlasdairGray** [comment]
It works for me now.

**Comment by beta2k** [comment]
when I wrote my [first reply](https://github.com/streamreasoning/RSP-QL/issues/15#issuecomment-116519131) here, I also experienced the same issue as you, but then it seemed to work. Maybe there are/were some issues on the server side.

If someone else also experiences (timeout) errors when accessing [1], then please report here.

[1] http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/streamreasoning/RSP-QL/master/TimeVocab.owl
