### ISSUE TITLE
Refine terminology about RDF Streams

### ISSUE THREAD

**Issue by greenTara** [streamreasoning/RSP-QL#30]
There is a need to distinguish RDF streams that have only predicates whose associated order is total.
(Because there are number of important considerations that depend on this property, so it will be a great convenience to have a term for just these kinds of RDF streams.)

Some options:
1. Use a different term (e.g. RDF braid) for all things that are currently called RDF streams, and use the term "RDF stream" for only those with "totally-ordered predicates.
2. Retain the term RDF stream for the more general class, as it is now and create a new term, e.g. "RDF totally-ordered stream" or "RDF t.o.-stream"

**Comment by dellaglio** [comment]
I would go with the second option, principally to keep the general idea of "stream" as defined in other areas

**Comment by greenTara** [comment]
@dellaglio Thanks for the input. The second option is pretty much the way the document is written now.

**Comment by beta2k** [comment]
Sorry, for being late to the party, but I'd also go for the second option. The first pretty much would clash with the available existing literature which should be avoided.

**Comment by greenTara** [comment]
resolved with no change to current terminology
