### ISSUE TITLE
functional requirements do not provide details about query operators

### ISSUE THREAD

**Issue by jpcik** [streamreasoning/RSP-QL#43]
The Functional Requirements section could explicitly mention what operators an RSP-QL language should support. This could be too specific, so it may depend on the level of granularity we want to give to this seciton.

**Comment by greenTara** [comment]
It could be a helpful approach (at least from my perspective) to start mentioning such things even if they are too specific. It is easier to generalize if there is too much detail than to specialize when there is not enough detail. After a more general requirement is formulated, these could be retained as examples.
